openapi: 3.2.0
info:
  title: AutoCompose Knowledge Base API
  description: 'Autocompose API to suggest the next agent message.

    Suggestions are based on the conversation history, conversation metadata, and

    the in-progress message text the agent has already typed into the composer.'
  version: 0.0.3
servers:
- url: https://api.sandbox.asapp.com
- url: https://api.test.asapp.com
tags:
- name: Knowledge Base
  description: Operations to submit and retrieve Articles to the GenerativeAgent Knowledge Base.
  x-displayName: Knowledge Base
paths:
  /knowledge-base/v1/submissions:
    post:
      tags:
      - Knowledge Base
      summary: Create a submission
      description: 'Initiate a request to add a new article or update an existing one.


        The provided title and content will be processed to create the final version of the submission.


        A `submission` is the programmatic creation or editing of an article. All submissions need to be approved by a human in the ASAPP Console in order to be applied.


        All content in a submission may be refined by our AI in order to make it easy to be used by GenerativeAgent


        Head to Connecting your Knowledge Base to see how to enter the API from the ASAPP Console.'
      operationId: createSubmission
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubmissionRequest'
      responses:
        '201':
          description: Submission successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Submission'
              example:
                id: fddd060c-22d7-4aed-acae-8f8dcc093a88
                articleId: 8f8dcc09-22d7-4aed-acae-fddd060c3a88
                submittedAt: '2024-12-12T00:00:00'
                title: 5G Data Plan
                content: Our 5G data plans offer lightning-fast speeds and generous data allowances. The Basic 5G plan includes 50GB of data per month, while our Unlimited 5G plan offers truly unlimited data with no speed caps. Both plans include unlimited calls and texts within the country. International roaming can be added for an additional fee.
                url: https://example.com/5g-data-plans
                metadata:
                - key: department
                  value: Customer experience
                queryExamples:
                - What 5G plans do you offer?
                - Is there an unlimited 5G plan?
                additionalInstructions:
                - clarificationInstruction: Emphasize that 5G coverage may vary by location
                  exampleResponse: Our 5G plans offer great speeds and data allowances, but please note that 5G coverage may vary depending on your location. You can check coverage in your area on our website.
                status: PENDING_REVIEW
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '413':
          $ref: '#/components/responses/RequestEntityTooLarge'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
        default:
          $ref: '#/components/responses/DefaultError'
      security:
      - API-ID: []
        API-Secret: []
  /knowledge-base/v1/submissions/{id}:
    get:
      tags:
      - Knowledge Base
      summary: Retrieve a submission
      description: 'This service retrieves the details of a specific submission using its unique identifier.


        A `submission` is the programmatic creation or editing of an article. All submissions need to be approved by a human in the ASAPP Console in order to be applied.


        All content in a submission may be refined by our AI in order to make it easy to be used by GenerativeAgent


        Head to Connecting your Knowledge Base to see how to enter the API from the ASAPP Console.'
      operationId: getSubmission
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
        description: The unique identifier for the submission to be retrieved.
        example: fddd060c-22d7-4aed-acae-8f8dcc093a88
      responses:
        '200':
          description: Submission successfully retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Submission'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
        default:
          $ref: '#/components/responses/DefaultError'
      security:
      - API-ID: []
        API-Secret: []
  /knowledge-base/v1/articles/{id}:
    get:
      tags:
      - Knowledge Base
      summary: Retrieve an article
      description: 'Fetch a specific article by its unique identifier.


        If the article has not been created because the associated submission was not approved, a 404 status will be returned.'
      operationId: getArticle
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
        description: The unique identifier for the article to be retrieved.
        example: 8f8dcc09-22d7-4aed-acae-fddd060c3a88
      responses:
        '200':
          description: Article successfully retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Article'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
        default:
          $ref: '#/components/responses/DefaultError'
      security:
      - API-ID: []
        API-Secret: []
components:
  schemas:
    ServiceUnavailableResponse:
      description: Service Unavailable response
      type: object
      properties:
        error:
          $ref: '#/components/schemas/DefaultErrorDetails'
          example:
            requestId: 8e033668-9f1a-11ec-b909-0242ac120002
            code: 503-01
            message: Service Unavailable
    DefaultErrorResponse:
      description: Default error response
      type: object
      properties:
        error:
          $ref: '#/components/schemas/DefaultErrorDetails'
          example:
            requestId: 8e033668-9f1a-11ec-b909-0242ac120002
            code: 500-01
            message: Internal server error
    Article:
      description: An article stored within the Knowledge Base.
      type: object
      properties:
        id:
          type: string
          description: The unique identifier for the article.
          example: fddd060c-22d7-4aed-acae-8f8dcc093a88
        title:
          type: string
          description: The refined title of the article, resulting from the cleanup process.
          example: 5G Data Plan Overview
        content:
          type: string
          description: The refined content of the article, resulting from the cleanup process.
          example: Our 5G data plans includes 75GB of data per month, while the Unlimited 5G plan offers unlimited data with no speed caps. Both plans include unlimited calls and texts within the country. International roaming is available for an additional fee.
        url:
          type: string
          description: The reference URL of the article. Defaults to null if not provided.
          example: https://example.com/5g-data-plans
        updatedAt:
          type: string
          format: date-time
          description: The timestamp indicating when the article was last updated. This field is null if the initial submission is still pending review.
          example: '2024-12-12T00:00:00Z'
        updatedBy:
          type: string
          description: The email address of the user who last updated the article. This field is null if the initial submission is still pending review.
          example: user@company.com
        metadata:
          type: array
          items:
            $ref: '#/components/schemas/Metadata'
          description: Additional key-value pairs related to the article.
          example:
          - key: department
            value: Customer experience
        originalContent:
          type: string
          description: The original content of the article prior to the cleanup process.
          example: Our 5G data plans offer lightning-fast speeds and generous data allowances. The Basic 5G plan now includes 75GB of data per month, while our Unlimited 5G plan offers truly unlimited data with no speed caps. Both plans include unlimited calls and texts within the country. International roaming can be added for an additional fee.
        originalTitle:
          type: string
          description: The original title of the article prior to the cleanup process.
          example: 5G Data Plan
        queryExamples:
          type: array
          items:
            type: string
          description: Examples of customer questions related to the article. Defaults to an empty array if not provided.
          example:
          - What 5G plans do you offer?
          - Is there a family plan for 5G?
        additionalInstructions:
          type: array
          items:
            $ref: '#/components/schemas/AdditionalInstruction'
          description: Specific instructions to ensure responses are relevant and address exceptions.
          example:
          - clarificationInstruction: Emphasize that 5G coverage may vary by location and mention the new Family Plan option
            exampleResponse: Our 5G plans offer great speeds and data allowances, including our new Family Plan. Please note that 5G coverage may vary depending on your location. You can check coverage in your area on our website.
        pendingSubmissionId:
          type: string
          description: The unique identifier for the submission currently under review for this article. This field is null if there are no pending submissions.
          example: 86ba487a-6d58-4b4c-82de-9d422f1166ae
        currentVersion:
          type: string
          description: The current version label of the article. This field is null if the initial submission is still pending review.
          example: v1
        deploymentStatus:
          $ref: '#/components/schemas/DeploymentStatus'
          description: The current deployment status of the article.
          example: DRAFT
      example:
        id: fddd060c-22d7-4aed-acae-8f8dcc093a88
        updatedAt: '2024-12-12T00:00:00'
        updatedBy: user@company.com
        title: 5G Data Plan Overview
        content: Our 5G data plans includes 75GB of data per month, while the Unlimited 5G plan offers unlimited data with no speed caps. Both plans include unlimited calls and texts within the country. International roaming is available for an additional fee.
        url: https://example.com/5g-data-plans
        metadata:
        - key: department
          value: Customer experience
        originalContent: Our 5G data plans offer lightning-fast speeds and generous data allowances. The Basic 5G plan now includes 75GB of data per month, while our Unlimited 5G plan offers truly unlimited data with no speed caps. Both plans include unlimited calls and texts within the country. International roaming can be added for an additional fee.
        originalTitle: 5G Data Plan
        queryExamples:
        - What 5G plans do you offer?
        - Is there a family plan for 5G?
        additionalInstructions:
        - clarificationInstruction: Emphasize that 5G coverage may vary by location and mention the new Family Plan option
          exampleResponse: Our 5G plans offer great speeds and data allowances, including our new Family Plan. Please note that 5G coverage may vary depending on your location. You can check coverage in your area on our website.
        pendingSubmissionId: 86ba487a-6d58-4b4c-82de-9d422f1166ae
        currentVersion: v1
        deploymentStatus: DRAFT
    SubmissionStatus:
      description: The current status of the submission.
      type: string
      enum:
      - PENDING_REVIEW
      - ACCEPTED
      - REJECTED
      example: PENDING_REVIEW
    ForbiddenResponse:
      description: Forbidden response
      type: object
      properties:
        error:
          $ref: '#/components/schemas/DefaultErrorDetails'
          example:
            requestId: 8e033668-9f1a-11ec-b909-0242ac120002
            code: 403-01
            message: Forbidden Response
    Submission:
      description: Information about a successfully submitted proposal to update an article in the Knowledge Base.
      type: object
      properties:
        id:
          type: string
          description: The unique identifier for the submission.
          example: fddd060c-22d7-4aed-acae-8f8dcc093a88
        articleId:
          type: string
          description: The unique identifier for the article related to the submission.
          example: 8f8dcc09-22d7-4aed-acae-fddd060c3a88
        submittedAt:
          type: string
          format: date-time
          description: The timestamp when the submission was created.
          example: '2024-12-12T00:00:00Z'
        title:
          type: string
          description: The article title, either original or refined.
          example: 5G Data Plan
        content:
          type: string
          description: The article content, either original or refined.
          example: Our 5G data plans offer lightning-fast speeds and generous data allowances. The Basic 5G plan includes 50GB of data per month, while our Unlimited 5G plan offers truly unlimited data with no speed caps. Both plans include unlimited calls and texts within the country. International roaming can be added for an additional fee.
        url:
          type: string
          description: The reference URL of the article. Defaults to an empty string if not provided.
          example: https://example.com/5g-data-plans
        metadata:
          type: array
          items:
            $ref: '#/components/schemas/Metadata'
          description: Additional key-value pairs related to the article.
          example:
          - key: department
            value: Customer experience
        queryExamples:
          type: array
          items:
            type: string
          description: Examples of customer questions related to the article. Defaults to an empty array if not provided.
          example:
          - What 5G plans do you offer?
          - Is there an unlimited 5G plan?
        additionalInstructions:
          type: array
          items:
            $ref: '#/components/schemas/AdditionalInstruction'
          description: Specific instructions to ensure responses are relevant and address exceptions.
          example:
          - clarificationInstruction: Emphasize that 5G coverage may vary by location
            exampleResponse: Our 5G plans offer great speeds and data allowances, but please note that 5G coverage may vary depending on your location. You can check coverage in your area on our website.
        status:
          $ref: '#/components/schemas/SubmissionStatus'
          description: The current status of the submission.
          example: PENDING_REVIEW
    Metadata:
      description: A key-value pair providing additional information about the article.
      type: object
      required:
      - key
      - value
      properties:
        key:
          type: string
          minLength: 1
          description: The key for the metadata entry.
          example: department
        value:
          type: string
          minLength: 1
          description: The value for the metadata entry.
          example: Customer experience
    DefaultErrorDetails:
      description: Error details
      type: object
      properties:
        requestId:
          type: string
          description: Unique ID of the failing request
        message:
          type: string
          description: Error message
        code:
          type: string
          description: Error code
      required:
      - requestId
      - message
    UnauthorizedResponse:
      description: Unauthorized response
      type: object
      properties:
        error:
          $ref: '#/components/schemas/DefaultErrorDetails'
          example:
            requestId: 8e033668-9f1a-11ec-b909-0242ac120002
            code: 401-01
            message: Unauthorized
    TooManyRequestsResponse:
      description: Too Many Requests response
      type: object
      properties:
        error:
          $ref: '#/components/schemas/DefaultErrorDetails'
          example:
            requestId: 8e033668-9f1a-11ec-b909-0242ac120002
            code: 429-01
            message: Too Many Requests
    DeploymentStatus:
      description: The current deployment status of the article.
      type: string
      enum:
      - NONE
      - DRAFT
      - SANDBOX
      - PRODUCTION
      - SANDBOX_AND_PRODUCTION
      example: DRAFT
    NotFoundResponse:
      description: Not Found response
      type: object
      properties:
        error:
          $ref: '#/components/schemas/DefaultErrorDetails'
          example:
            requestId: 8e033668-9f1a-11ec-b909-0242ac120002
            code: 404-01
            message: Not Found
    BadRequestResponse:
      description: Bad request response
      type: object
      properties:
        error:
          $ref: '#/components/schemas/DefaultErrorDetails'
          example:
            requestId: 8e033668-9f1a-11ec-b909-0242ac120002
            code: 400-01
            message: Bad request
    RequestEntityTooLargeResponse:
      description: Request Entity Too Large response
      type: object
      properties:
        error:
          $ref: '#/components/schemas/DefaultErrorDetails'
          example:
            requestId: 8e033668-9f1a-11ec-b909-0242ac120002
            code: 413-01
            message: Request Entity Too Large
    SubmissionRequest:
      description: A proposal for creating a new article or updating an existing one in the Knowledge Base.
      type: object
      properties:
        articleId:
          type: string
          description: The unique identifier for the article being updated.
          example: 8f8dcc09-22d7-4aed-acae-fddd060c3a88
        title:
          type: string
          description: The proposed title of the article, which will be refined automatically. This is required for new articles.
          minLength: 1
          maxLength: 256
          example: 5G Data Plan
        content:
          type: string
          description: The article content in plain text, expected to be in English and limited to 200,000 Unicode characters. This will be refined during submission. Required for new articles.
          minLength: 1
          maxLength: 200000
          example: Our 5G data plans offer lightning-fast speeds and generous data allowances. The Basic 5G plan includes 50GB of data per month, while our Unlimited 5G plan offers truly unlimited data with no speed caps. Both plans include unlimited calls and texts within the country. International roaming can be added for an additional fee.
        url:
          type: string
          description: A reference URL for the article, used for informational purposes only.
          example: https://example.com/5g-data-plans
        metadata:
          type: array
          items:
            $ref: '#/components/schemas/Metadata'
          description: Additional key-value pairs related to the article.
          example:
          - key: department
            value: Customer experience
        queryExamples:
          type: array
          items:
            type: string
          description: Examples of customer questions related to the article, such as "Why is my bill so high?". Defaults to an empty list if not provided.
          example:
          - What 5G plans do you offer?
          - Is there an unlimited 5G plan?
        additionalInstructions:
          type: array
          items:
            $ref: '#/components/schemas/AdditionalInstruction'
          description: Specific instructions to ensure responses are relevant and address exceptions.
          example:
          - clarificationInstruction: Emphasize that 5G coverage may vary by location
            exampleResponse: Our 5G plans offer great speeds and data allowances, but please note that 5G coverage may vary depending on your location. You can check coverage in your area on our website.
      example:
        title: 5G Data Plan
        content: Our 5G data plans offer lightning-fast speeds and generous data allowances. The Basic 5G plan includes 50GB of data per month, while our Unlimited 5G plan offers truly unlimited data with no speed caps. Both plans include unlimited calls and texts within the country. International roaming can be added for an additional fee.
        url: https://example.com/5g-data-plans
        metadata:
        - key: department
          value: Customer experience
        queryExamples:
        - What 5G plans do you offer?
        - Is there an unlimited 5G plan?
        additionalInstructions:
        - clarificationInstruction: Emphasize that 5G coverage may vary by location
          exampleResponse: Our 5G plans offer great speeds and data allowances, but please note that 5G coverage may vary depending on your location. You can check coverage in your area on our website.
    AdditionalInstruction:
      description: Guidelines and responses to enhance the article.
      type: object
      properties:
        clarificationInstruction:
          type: string
          description: A guideline to improve the article's content.
          example: Emphasize that 5G coverage may vary by location
        exampleResponse:
          type: string
          description: A sample response applicable if the clarification instruction is followed.
          example: Our 5G plans offer great speeds and data allowances, but please note that 5G coverage may vary depending on your location. You can check coverage in your area on our website.
  responses:
    RequestEntityTooLarge:
      description: 413 - Request Entity Too Large
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RequestEntityTooLargeResponse'
    DefaultError:
      description: 500 - Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DefaultErrorResponse'
    Unauthorized:
      description: 401 - Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UnauthorizedResponse'
    ServiceUnavailable:
      description: 503 - Service Unavailable
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ServiceUnavailableResponse'
    TooManyRequests:
      description: 429 - Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TooManyRequestsResponse'
    NotFound:
      description: 404 - Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/NotFoundResponse'
    BadRequest:
      description: 400 - Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BadRequestResponse'
    Forbidden:
      description: 403 - Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ForbiddenResponse'
  securitySchemes:
    API-ID:
      type: apiKey
      in: header
      name: asapp-api-id
    API-Secret:
      type: apiKey
      in: header
      name: asapp-api-secret
x-tagGroups:
- name: AutoCompose API
  tags:
  - AutoCompose
- name: AutoSummary API
  tags:
  - AutoSummary
- name: AutoTranscribe API
  tags:
  - AutoTranscribe
- name: Conversations API
  tags:
  - Conversations
- name: File Exporter API
  tags:
  - File Exporter
- name: GenerativeAgent API
  tags:
  - GenerativeAgent
- name: Health Check API
  tags:
  - Health Check
- name: Knowledge Base API
  tags:
  - Knowledge Base
- name: Metadata Ingestion API
  tags:
  - Metadata
- name: MG Autotranscribe API Router
  tags:
  - AutoTranscribe Media Gateway
