openapi: 3.2.0
info:
  title: AutoCompose File Exporter API
  description: 'Autocompose API to suggest the next agent message.

    Suggestions are based on the conversation history, conversation metadata, and

    the in-progress message text the agent has already typed into the composer.'
  version: 0.0.3
servers:
- url: https://api.sandbox.asapp.com
- url: https://api.test.asapp.com
tags:
- name: File Exporter
  description: API to get client exports
  x-displayName: File Exporter
paths:
  /fileexporter/v1/static/listfeeds:
    post:
      tags:
      - File Exporter
      operationId: listFeeds
      summary: List feeds
      description: Lists feed names for a company
      responses:
        '200':
          description: Successfully requested feed names
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListFeedsResponse'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        default:
          $ref: '#/components/responses/DefaultError'
      security:
      - API-ID: []
        API-Secret: []
  /fileexporter/v1/static/listfeedversions:
    post:
      tags:
      - File Exporter
      operationId: listFeedVersions
      summary: List feed versions
      description: Lists feed versions for a company
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ListFeedVersionsRequest'
      responses:
        '200':
          description: Successfully requested feed versions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListFeedVersionsResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          $ref: '#/components/responses/Conflict'
        '413':
          $ref: '#/components/responses/RequestEntityTooLarge'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
        default:
          $ref: '#/components/responses/DefaultError'
      security:
      - API-ID: []
        API-Secret: []
  /fileexporter/v1/static/listfeedformats:
    post:
      tags:
      - File Exporter
      operationId: listFeedFormats
      summary: List feed formats
      description: Lists feed formats for a company feed/version/
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ListFeedFormatsRequest'
      responses:
        '200':
          description: Successfully requested feed formats
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListFeedFormatsResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          $ref: '#/components/responses/Conflict'
        '413':
          $ref: '#/components/responses/RequestEntityTooLarge'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
        default:
          $ref: '#/components/responses/DefaultError'
      security:
      - API-ID: []
        API-Secret: []
  /fileexporter/v1/static/listfeeddates:
    post:
      tags:
      - File Exporter
      operationId: listFeedDates
      summary: List feed dates
      description: Lists dates for a company feed/version/format
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ListFeedDatesRequest'
      responses:
        '200':
          description: Successfully requested feed dates
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListFeedDatesResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          $ref: '#/components/responses/Conflict'
        '413':
          $ref: '#/components/responses/RequestEntityTooLarge'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
        default:
          $ref: '#/components/responses/DefaultError'
      security:
      - API-ID: []
        API-Secret: []
  /fileexporter/v1/static/listfeedintervals:
    post:
      tags:
      - File Exporter
      operationId: listFeedIntervals
      summary: List feed intervals
      description: Lists intervals for a company feed/version/format/date
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ListFeedIntervalsRequest'
      responses:
        '200':
          description: Successfully requested feed intervals
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListFeedIntervalsResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          $ref: '#/components/responses/Conflict'
        '413':
          $ref: '#/components/responses/RequestEntityTooLarge'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
        default:
          $ref: '#/components/responses/DefaultError'
      security:
      - API-ID: []
        API-Secret: []
  /fileexporter/v1/static/listfeedfiles:
    post:
      tags:
      - File Exporter
      operationId: listFeedFiles
      summary: List feed files
      description: Lists files for a company feed/version/format/date/interval
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ListFeedFilesRequest'
      responses:
        '200':
          description: Successfully requested feed files
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListFeedFilesResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          $ref: '#/components/responses/Conflict'
        '413':
          $ref: '#/components/responses/RequestEntityTooLarge'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
        default:
          $ref: '#/components/responses/DefaultError'
      security:
      - API-ID: []
        API-Secret: []
  /fileexporter/v1/static/getfeedfile:
    post:
      tags:
      - File Exporter
      operationId: listFeedFile
      summary: Retrieve a feed file
      description: Retrieves a feed file URL for a company feed/version/format/date/interval/file
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetFeedFileRequest'
      responses:
        '200':
          description: Successfully requested feed file
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetFeedFileResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          $ref: '#/components/responses/Conflict'
        '413':
          $ref: '#/components/responses/RequestEntityTooLarge'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
        default:
          $ref: '#/components/responses/DefaultError'
      security:
      - API-ID: []
        API-Secret: []
components:
  schemas:
    ServiceUnavailableResponse:
      description: Service Unavailable response
      type: object
      properties:
        error:
          $ref: '#/components/schemas/DefaultErrorDetails'
          example:
            requestId: 8e033668-9f1a-11ec-b909-0242ac120002
            code: 503-01
            message: Service Unavailable
    DefaultErrorResponse:
      description: Default error response
      type: object
      properties:
        error:
          $ref: '#/components/schemas/DefaultErrorDetails'
          example:
            requestId: 8e033668-9f1a-11ec-b909-0242ac120002
            code: 500-01
            message: Internal server error
    ListFeedFilesRequest:
      description: Get files for a company feed/version/format/date/interval
      type: object
      properties:
        feed:
          type: string
          example: feed_test
        version:
          type: string
          example: '1'
        format:
          type: string
          example: jsonl
        date:
          type: string
          example: '2022-06-27'
        interval:
          type: string
          example: hr=23
      required:
      - feed
      - version
      - format
      - date
      example:
        feed: feed_test
        version: '1'
        format: jsonl
        date: '2022-06-27'
        interval: hr=23
    ListFeedVersionsResponse:
      description: Get versions for a company feed
      type: object
      properties:
        feed:
          type: string
          example: feed_test
        versions:
          type: array
          items:
            type: string
          example:
          - '1'
          - '2'
          - '3'
    GetFeedFileRequest:
      description: Get file for a company feed/version/format/interval/file
      type: object
      properties:
        feed:
          type: string
          example: feed_test
        version:
          type: string
          example: '1'
        format:
          type: string
          example: jsonl
        date:
          type: string
          example: '2022-06-27'
        interval:
          type: string
          example: hr=23
        fileName:
          type: string
          example: file1.jsonl
      required:
      - feed
      - version
      - format
      - date
      - fileName
      example:
        feed: feed_test
        version: '1'
        format: jsonl
        date: '2022-06-27'
        interval: hr=23
        fileName: file1.jsonl
    ListFeedDatesResponse:
      description: Get Dates for a company feed/version/format
      type: object
      properties:
        feed:
          type: string
          example: feed_test
        version:
          type: string
          example: '1'
        format:
          type: string
          example: format=jsonl
        dates:
          type: array
          items:
            type: string
          example:
          - '2022-06-27'
          - '2022-05-20'
          - '2022-05-21'
    ListFeedFilesResponse:
      description: Get files for a company feed/version/format/date/interval
      type: object
      properties:
        feed:
          type: string
          example: feed_test
        version:
          type: string
          example: '1'
        format:
          type: string
          example: jsonl
        date:
          type: string
          example: '2022-06-27'
        interval:
          type: string
          example: hr=23
        files:
          type: array
          items:
            type: string
          example:
          - file1.jsonl
          - file2.json1
    GetFeedFileResponse:
      description: Get a presigned url for a file
      type: object
      properties:
        feed:
          type: string
          example: feed_test
        version:
          type: string
          example: '1'
        format:
          type: string
          example: jsonl
        date:
          type: string
          example: '2022-06-27'
        interval:
          type: string
          example: hr=23
        fileName:
          type: string
          example: file1.json1
        url:
          type: string
          example: www.example.com/12381273972817312/file1.json1
    ForbiddenResponse:
      description: Forbidden response
      type: object
      properties:
        error:
          $ref: '#/components/schemas/DefaultErrorDetails'
          example:
            requestId: 8e033668-9f1a-11ec-b909-0242ac120002
            code: 403-01
            message: Forbidden Response
    ListFeedVersionsRequest:
      description: Get versions for a company feed
      type: object
      properties:
        feed:
          type: string
          example: feed_test
      required:
      - feed
      example:
        feed: feed_test
    ConflictResponse:
      description: Conflict response
      type: object
      properties:
        error:
          $ref: '#/components/schemas/DefaultErrorDetails'
          example:
            requestId: 8e033668-9f1a-11ec-b909-0242ac120002
            code: 409-01
            message: Conflict
    ListFeedsResponse:
      description: Get feed names for a company
      type: object
      properties:
        feeds:
          type: array
          items:
            type: string
          example:
          - feed_1
          - feed_2
          - feed_3
    ListFeedDatesRequest:
      description: Get dates for a company feed/version/format
      type: object
      properties:
        feed:
          type: string
          example: feed_test
        version:
          type: string
          example: '1'
        format:
          type: string
          example: jsonl
      required:
      - feed
      - version
      - format
      example:
        feed: feed_test
        version: '1'
        format: jsonl
    DefaultErrorDetails:
      description: Error details
      type: object
      properties:
        requestId:
          type: string
          description: Unique ID of the failing request
        message:
          type: string
          description: Error message
        code:
          type: string
          description: Error code
      required:
      - requestId
      - message
    UnauthorizedResponse:
      description: Unauthorized response
      type: object
      properties:
        error:
          $ref: '#/components/schemas/DefaultErrorDetails'
          example:
            requestId: 8e033668-9f1a-11ec-b909-0242ac120002
            code: 401-01
            message: Unauthorized
    ListFeedFormatsResponse:
      description: Get formats for a company feed
      type: object
      properties:
        feed:
          type: string
          example: feed_test
        version:
          type: string
          example: '1'
        formats:
          type: array
          items:
            type: string
          example:
          - jsonl
          - csv
    ListFeedIntervalsResponse:
      description: Get Dates for a company feed/version/format
      type: object
      properties:
        feed:
          type: string
          example: feed_test
        version:
          type: string
          example: '1'
        format:
          type: string
          example: jsonl
        date:
          type: string
          example: '2022-06-27'
        intervals:
          type: array
          items:
            type: string
          example:
          - hr=01/mi=01
          - hr=01/mi=02
    TooManyRequestsResponse:
      description: Too Many Requests response
      type: object
      properties:
        error:
          $ref: '#/components/schemas/DefaultErrorDetails'
          example:
            requestId: 8e033668-9f1a-11ec-b909-0242ac120002
            code: 429-01
            message: Too Many Requests
    NotFoundResponse:
      description: Not Found response
      type: object
      properties:
        error:
          $ref: '#/components/schemas/DefaultErrorDetails'
          example:
            requestId: 8e033668-9f1a-11ec-b909-0242ac120002
            code: 404-01
            message: Not Found
    BadRequestResponse:
      description: Bad request response
      type: object
      properties:
        error:
          $ref: '#/components/schemas/DefaultErrorDetails'
          example:
            requestId: 8e033668-9f1a-11ec-b909-0242ac120002
            code: 400-01
            message: Bad request
    ListFeedIntervalsRequest:
      description: Get intervals for a company feed/version/format/date
      type: object
      properties:
        feed:
          type: string
          example: feed_test
        version:
          type: string
          example: '1'
        format:
          type: string
          example: jsonl
        date:
          type: string
          example: '2022-06-27'
      required:
      - feed
      - version
      - format
      - date
      example:
        feed: feed_test
        version: '1'
        format: jsonl
        date: '2022-06-27'
    RequestEntityTooLargeResponse:
      description: Request Entity Too Large response
      type: object
      properties:
        error:
          $ref: '#/components/schemas/DefaultErrorDetails'
          example:
            requestId: 8e033668-9f1a-11ec-b909-0242ac120002
            code: 413-01
            message: Request Entity Too Large
    ListFeedFormatsRequest:
      description: Get format for a company feed/version
      type: object
      properties:
        feed:
          type: string
          example: feed_test
        version:
          type: string
          example: '1'
      required:
      - feed
      - version
      example:
        feed: feed_test
        version: '1'
    UnprocessableEntity:
      description: Unprocessable Entity response
      type: object
      properties:
        error:
          $ref: '#/components/schemas/DefaultErrorDetails'
          example:
            requestId: 8e033668-9f1a-11ec-b909-0242ac120002
            code: 422-01
            message: Unprocessable Entity
  responses:
    RequestEntityTooLarge:
      description: 413 - Request Entity Too Large
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RequestEntityTooLargeResponse'
    Conflict:
      description: 409 - Conflict
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ConflictResponse'
    DefaultError:
      description: 500 - Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DefaultErrorResponse'
    Unauthorized:
      description: 401 - Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UnauthorizedResponse'
    ServiceUnavailable:
      description: 503 - Service Unavailable
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ServiceUnavailableResponse'
    TooManyRequests:
      description: 429 - Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TooManyRequestsResponse'
    NotFound:
      description: 404 - Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/NotFoundResponse'
    BadRequest:
      description: 400 - Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BadRequestResponse'
    UnprocessableEntity:
      description: 422 - Unprocessable Entity
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UnprocessableEntity'
    Forbidden:
      description: 403 - Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ForbiddenResponse'
  securitySchemes:
    API-ID:
      type: apiKey
      in: header
      name: asapp-api-id
    API-Secret:
      type: apiKey
      in: header
      name: asapp-api-secret
x-tagGroups:
- name: AutoCompose API
  tags:
  - AutoCompose
- name: AutoSummary API
  tags:
  - AutoSummary
- name: AutoTranscribe API
  tags:
  - AutoTranscribe
- name: Conversations API
  tags:
  - Conversations
- name: File Exporter API
  tags:
  - File Exporter
- name: GenerativeAgent API
  tags:
  - GenerativeAgent
- name: Health Check API
  tags:
  - Health Check
- name: Knowledge Base API
  tags:
  - Knowledge Base
- name: Metadata Ingestion API
  tags:
  - Metadata
- name: MG Autotranscribe API Router
  tags:
  - AutoTranscribe Media Gateway
